version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/ddl:/docker-entrypoint-initdb.d
#      # 永続化するときにマウントするdir
#      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password